export { AboutMe } from './aboutMe/AboutMe'
export { Contact } from './contact/Contact'
export { Experience } from './experience/Experience'
export { Hero } from './hero/Hero'
export { Projects } from './projects/Projects'
export { Skills } from './skills/Skills'
